<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <defaultLandingTab>standard-home</defaultLandingTab>
    <label>BoothLeads2.0DEV</label>
    <tab>BL_Pricing__c</tab>
    <tab>Profile__c</tab>
    <tab>Event__c</tab>
    <tab>EventSchedule__c</tab>
    <tab>DataImport_SavePoint__c</tab>
    <tab>AttendeeSummary__c</tab>
    <tab>Event_Attendee_Mapping__c</tab>
    <tab>Booth__c</tab>
    <tab>Booth_Product__c</tab>
    <tab>BoothVisitSummary__c</tab>
    <tab>User_Event_BVS__c</tab>
    <tab>SecurityControls__c</tab>
    <tab>User_CheckinHistory__c</tab>
    <tab>User_Profile_Event__c</tab>
    <tab>User_PaidHistory__c</tab>
    <tab>Reports__c</tab>
    <tab>Event_Invitee__c</tab>
    <tab>TicketTypes__c</tab>
    <tab>AttendeePaidHistory__c</tab>
    <tab>Booth_Qrcode__c</tab>
    <tab>DeviceUsage__c</tab>
    <tab>Pay_Pal_Account__c</tab>
    <tab>Dummay__c</tab>
    <tab>Ticket_Eam__c</tab>
    <tab>Constomer__c</tab>
    <tab>Non_Attendee__c</tab>
    <tab>Survey_Questions__c</tab>
    <tab>Survey__c</tab>
    <tab>Ticket_Mapswith_Survey__c</tab>
    <tab>Promocodes__c</tab>
    <tab>Tickets_Mapswith_Promocode__c</tab>
    <tab>Registration_ticket_settings__c</tab>
    <tab>Registration_Settings__c</tab>
    <tab>Event_Registration_jun__c</tab>
    <tab>Item__c</tab>
    <tab>Track__c</tab>
    <tab>Seminar__c</tab>
    <tab>Scheduled_Fields__c</tab>
    <tab>Ticket_iteam_jun__c</tab>
    <tab>Event_Breaks__c</tab>
    <tab>MatchLeads_Days__c</tab>
    <tab>NAICS_Code__c</tab>
    <tab>BadgeTemplate_Styles__c</tab>
    <tab>Floor_Map__c</tab>
    <tab>Tags__c</tab>
    <tab>Ticket_Session_Mapping__c</tab>
    <tab>Commodities__c</tab>
    <tab>Profile_Settings__c</tab>
    <tab>Custom_Widget__c</tab>
    <tab>MBE_Profile__c</tab>
    <tab>MMQuestion__c</tab>
    <tab>Qaj__c</tab>
</CustomApplication>
