public class BL_BadgeSettingsClass{

    public  List<SelectOption> fontface() {
        List<SelectOption> options = new List<SelectOption>();
        // options.add(new selectoption('select','Select Font Family'));
        options.add(new SelectOption('Agency FB','Agency FB'));
        options.add(new SelectOption('Algerian','Algerian'));
        options.add(new SelectOption('Arial','Arial'));
        options.add(new SelectOption('Arial Black','Arial Black'));
        options.add(new SelectOption('Arial Narrow','Arial Narrow'));
        options.add(new SelectOption('Arial Rounded MT Bold','Arial Rounded MT Bold'));
        options.add(new SelectOption('Arial Unicode MS','Arial Unicode MS'));
        options.add(new SelectOption('Baskerville Old Face','Baskerville Old Face'));
        options.add(new SelectOption('Bauhaus 93','Bauhaus 93'));
        options.add(new SelectOption('Bell MT','Bell MT'));
        options.add(new SelectOption('Berlin Sans FB','Berlin Sans FB'));
        options.add(new SelectOption('Arial','Arial'));            
        options.add(new SelectOption('Agency FB','Agency FB'));
        options.add(new SelectOption('Berlin Sans FB Demi','Berlin Sans FB Demi'));
        options.add(new SelectOption('Bernard MT Condensed','Bernard MT Condensed'));
        options.add(new selectoption('Blackadder ITC','Blackadder ITC'));
        options.add(new selectoption('Bodoni MT','Bodoni MT'));
        options.add(new selectoption('Bodoni MT Black','Bodoni MT Black'));
        options.add(new selectoption('Bodoni MT Condensed','Bodoni MT Condensed'));
        options.add(new selectoption('Bodoni MT Poster Compressed','Bodoni MT Poster Compressed'));
        options.add(new selectoption('Book Antiqua','Book Antiqua'));
        options.add(new selectoption('Bookman Old Style','Bookman Old Style'));
        options.add(new selectoption('Bookshelf Symbol 7','Bookshelf Symbol 7'));
        options.add(new selectoption('Bradley Hand ITC','Bradley Hand ITC'));
        options.add(new selectoption('Britannic Bold','Britannic Bold'));
        options.add(new selectoption('Broadway','Broadway'));
        options.add(new selectoption('Brush Script MT','Brush Script MT'));
        options.add(new selectoption('Calibri','Calibri'));
        options.add(new selectoption('Californian FB','Californian FB'));
        options.add(new selectoption('Calisto MT','Calisto MT'));
        options.add(new selectoption('Cambria','Cambria'));
        options.add(new selectoption('Cambria Math','Cambria Math'));
        options.add(new selectoption('Candara','Candara'));
        options.add(new selectoption('Castellar','Castellar'));
        options.add(new selectoption('Centaur','Centaur'));
        options.add(new selectoption('Century','Century'));
        options.add(new selectoption('Century Gothic','Century Gothic'));
        options.add(new selectoption('Century Schoolbook','Century Schoolbook'));
        options.add(new selectoption('Chiller','Chiller'));
        options.add(new selectoption('Colonna MT','Colonna MT'));
        options.add(new selectoption('Comic Sans MS','Comic Sans MS'));
        options.add(new selectoption('Consolas','Consolas'));
        options.add(new selectoption('Constantia','Constantia'));
        options.add(new selectoption('Cooper Black','Cooper Black'));
        options.add(new selectoption('Copperplate Gothic Bold','Copperplate Gothic Bold'));
        options.add(new selectoption('Copperplate Gothic Light','Copperplate Gothic Light'));
        options.add(new selectoption('Corbel','Corbel'));
        options.add(new selectoption('Courier New','Courier New'));
        options.add(new selectoption('Curlz MT','Curlz MT'));
        options.add(new selectoption('Engravers MT','Engravers MT'));
        options.add(new selectoption('Edwardian Script ITC','Edwardian Script ITC'));
        options.add(new selectoption('Elephant','Elephant'));
        options.add(new selectoption('Eras Demi ITC','Eras Demi ITC'));
        options.add(new selectoption('Estrangelo Edessa','Estrangelo Edessa'));
        options.add(new selectoption('Felix Titling','Felix Titling'));
        options.add(new selectoption('Footlight MT Light','Footlight MT Light'));
        options.add(new selectoption('Forte','Forte'));
        options.add(new selectoption('Franklin Gothic Book','Franklin Gothic Book'));
        options.add(new selectoption('Franklin Gothic Demi','Franklin Gothic Demi'));
        options.add(new selectoption('Franklin Gothic Demi Cond','Franklin Gothic Demi Cond'));
        options.add(new selectoption('Franklin Gothic Heavy','Franklin Gothic Heavy'));
        options.add(new selectoption('Franklin Gothic Medium','Franklin Gothic Medium'));
        options.add(new selectoption('Franklin Gothic Medium Cond','Franklin Gothic Medium Cond'));
        options.add(new selectoption('Franklin Gothic Heavy','Franklin Gothic Heavy'));
        options.add(new selectoption('Freestyle Script','Freestyle Script'));
        options.add(new selectoption('French Script MT','French Script MT'));
        options.add(new selectoption('Garamond','Garamond'));
        options.add(new selectoption('Gautami','Gautami'));
        options.add(new selectoption('Georgia','Georgia'));
        options.add(new selectoption('Gigi','Gigi'));
        options.add(new selectoption('Gill Sans MT','Gill Sans MT'));
        options.add(new selectoption('Gill Sans MT Condensed','Gill Sans MT Condensed'));
        options.add(new selectoption('Gill Sans MT Ext Condensed Bold','Gill Sans MT Ext Condensed Bold'));
        options.add(new selectoption('Gill Sans Ultra Bold','Gill Sans Ultra Bold'));
        options.add(new selectoption('Gill Sans Ultra Bold Condensed','Gill Sans Ultra Bold Condensed'));
        options.add(new selectoption('Gloucester MT Extra Condensed','Gloucester MT Extra Condensed'));
        options.add(new selectoption('Goudy Old Style','Goudy Old Style'));
        options.add(new selectoption('Goudy Stout','Goudy Stout'));
          options.add(new selectoption('Haettenschweiler','Haettenschweiler'));
          options.add(new selectoption('Harlow Solid Italic','Harlow Solid Italic'));
          options.add(new selectoption('Harrington','Harrington'));
          options.add(new selectoption('High Tower Text','High Tower Text'));
          options.add(new selectoption('Impact','Impact'));
          options.add(new selectoption('Imprint MT Shadow','Imprint MT Shadow'));
          options.add(new selectoption('Informal Roman','Informal Roman'));
          options.add(new selectoption('Jokerman','Jokerman'));
          options.add(new selectoption('Juice ITC', 'Juice ITC'));
          options.add(new selectoption('Kartika', 'Kartika'));
          options.add(new selectoption('Kristen ITC','Kristen ITC'));
          options.add(new selectoption('Kunstler Script', 'Kunstler Script'));
          options.add(new selectoption('Latha', 'Latha'));
          options.add(new selectoption('Lucida Bright', 'Lucida Bright'));
          options.add(new selectoption('Lucida Calligraphy', 'Lucida Calligraphy'));
          options.add(new selectoption('Lucida Console', 'Lucida Console'));
          options.add(new selectoption('Lucida Fax', 'Lucida Fax'));
          options.add(new selectoption('Lucida Sans Typewriter', 'Lucida Sans Typewriter'));
          options.add(new selectoption('Magneto','Magneto'));
          options.add(new selectoption('Maiandra GD','Maiandra GD'));
          options.add(new selectoption('Mangal','Mangal'));
          options.add(new selectoption('Marlett','Marlett'));
          options.add(new selectoption('Matura MT Script Capitals','Matura MT Script Capitals'));
          options.add(new selectoption('Microsoft Sans Serif','Microsoft Sans Serif'));
          options.add(new selectoption('Mistral','Mistral'));
          options.add(new selectoption('Modern No. 20','Modern No. 20'));
          options.add(new selectoption('Monotype Corsiva','Monotype Corsiva'));
          options.add(new selectoption('MS Mincho','MS Mincho'));
          options.add(new selectoption('MS Outlook','MS Outlook'));
          options.add(new selectoption('MS Reference Sans Serif','MS Reference Sans Serif'));
          options.add(new selectoption('MS Reference Specialty','MS Reference Specialty'));
          options.add(new selectoption('MT Extra','MT Extra'));
          options.add(new selectoption('MV Boli','MV Boli'));
          options.add(new selectoption('Niagara Engraved','Niagara Engraved'));
          options.add(new selectoption('Niagara Solid','Niagara Solid'));
          options.add(new selectoption('OCR A Extended','OCR A Extended'));
          options.add(new selectoption('Old English Text MT','Old English Text MT'));
          options.add(new selectoption('Onyx','Onyx'));
          options.add(new selectoption('Palace Script MT','Palace Script MT'));
          options.add(new selectoption('Palatino Linotype','Palatino Linotype'));
          options.add(new selectoption('Papyrus','Papyrus'));
          options.add(new selectoption('Parchment','Parchment'));
          options.add(new selectoption('Perpetua','Perpetua'));
          options.add(new selectoption('Perpetua Titling MT','Perpetua Titling MT'));
          options.add(new selectoption('Playbill','Playbill'));
          options.add(new selectoption('Poor Richard','Poor Richard'));
          options.add(new selectoption('Pristina','Pristina'));
          options.add(new selectoption('Raavi','Raavi'));
          options.add(new selectoption('Rage Italic','Rage Italic'));
          options.add(new selectoption('Rockwell','Rockwell'));
          options.add(new selectoption('Script MT Bold','Script MT Bold'));
           options.add(new selectoption('Shruti','Shruti'));
          options.add(new selectoption('Stencil','Stencil'));
          options.add(new selectoption('Symbol','Symbol'));
          options.add(new selectoption('Tahoma','Tahoma'));
          options.add(new selectoption('Tempus Sans ITC','Tempus Sans ITC'));
          options.add(new selectoption('Times New Roman','Times New Roman'));
          options.add(new selectoption('Trebuchet MS','Trebuchet MS'));
          options.add(new selectoption('Tunga','Tunga'));
          options.add(new selectoption('Tw Cen MT','Tw Cen MT'));
          options.add(new selectoption('Tw Cen MT Condensed','Tw Cen MT Condensed'));
          options.add(new selectoption('Lucida Sans Unicode', 'Lucida Sans Unicode'));
          options.add(new selectoption('Verdana', 'Verdana'));
          options.add(new selectoption('Viner Hand ITC','Viner Hand ITC'));
          options.add(new selectoption('Vivaldi', 'Vivaldi'));
          options.add(new selectoption('Vladimir Script', 'Vladimir Script'));
          options.add(new selectoption('Vrinda', 'Vrinda'));
          options.add(new selectoption('Webdings','Webdings'));
          options.add(new selectoption('Wide Latin','Wide Latin'));
          options.add(new selectoption('Wingdings','Wingdings'));
          options.add(new selectoption('Wingdings 2','Wingdings 2'));
          options.add(new selectoption('Wingdings 3','Wingdings 3')); 
         return options;    
    }
    
    public List<SelectOption> colors(){
            List<SelectOption> options = new List<SelectOption>();
           // options.add(new selectoption('select','Color'));
            options.add(new SelectOption('Green','Green'));
            options.add(new SelectOption('Red','Red'));
            options.add(new SelectOption('Pink','Pink'));
            options.add(new SelectOption('Orange','Orange'));
            options.add(new SelectOption('Blue','Blue'));
            options.add(new SelectOption('Indigo','Indigo'));
            options.add(new SelectOption('Black','Black'));
            return options;
            
    }

    public List<SelectOption> fieldnames(){
       List<SelectOption> options=new LIST<selectoption>();
      //  options.add(new selectoption('None','Select Fiels Name'));
        options.add(new selectoption('AS_LastName__c','LastName'));
        options.add(new selectoption('AS_FirstName__c','FirstName'));
        options.add(new selectoption('AS_Title__c','Designation'));
        options.add(new selectoption('AS_Company__c','Company'));
        return options;
    }
    
    public List<SelectOption> font(){
        LIST<selectoption> options=new LIST<selectoption>();
       // options.add(new selectoption('select','Font'));        
        
        options.add(new selectoption('30pt','30pt'));
        options.add(new selectoption('24pt','24pt'));
        options.add(new selectoption('18pt','18pt'));
        options.add(new selectoption('15pt','15pt'));
        
        return options;
    }
    public List<SelectOption> font1(){
        LIST<selectoption> options=new LIST<selectoption>();
       // options.add(new selectoption('select','Font'));                
        
        options.add(new selectoption('24pt','24pt'));
        options.add(new selectoption('18pt','18pt'));
        options.add(new selectoption('15pt','15pt'));
        
        return options;
    }
    public List<SelectOption> font2(){
        LIST<selectoption> options=new LIST<selectoption>();
       // options.add(new selectoption('select','Font'));                        
        options.add(new selectoption('18pt','18pt'));
        options.add(new selectoption('15pt','15pt'));
        options.add(new selectoption('12pt','12pt'));
        
        return options;
    }
    
    
     public List<SelectOption> font22806(){
        LIST<selectoption> options=new LIST<selectoption>();
      //  options.add(new selectoption('select','Font'));        
        options.add(new selectoption('20pt','20pt'));
        options.add(new selectoption('18pt','18pt'));
        options.add(new selectoption('15pt','15pt'));
        options.add(new selectoption('10pt','10pt'));
        
        return options;
    }
    
    public LIST<selectoption> fieldnames22806(){
        List<SelectOption> options = new List<SelectOption>();
         //   options.add(new selectoption('select','Select Field Names'));       
            options.add(new selectoption('AS_FirstName__c,AS_LastName__c','FirstName LastName'));        
            options.add(new selectoption('AS_Title__c','Designation'));
            options.add(new selectoption('AS_Company__c','Company'));
        return options; 
    }   
    

}