@isTest
public with sharing class Test_dummyforMLfor15{
 static testMethod void testmth(){
    dummyforMLfor15 dd = new dummyforMLfor15();
    dd.dummy11115for();
     dd.dummy2for();
     dd.dummy3for();
     dd.dummy4for();
     dd.dummy6for();
     dd.dummy7for();
     dd.dummy8for();
     dd.dummy9for();
     dd.dummy10for();
     dd.dummy11for();
     dd.dummy12for();
     dd.dummy13for();
 }

}